"""add_custom_workout_templates_and_plans

Revision ID: 2c804e25d9de
Revises: 003_add_user_profiles_and_race_schedules
Create Date: 2025-09-24 12:07:22.826097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c804e25d9de'
down_revision: Union[str, None] = '003_add_user_profiles_and_race_schedules'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_workout_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('plan_type', sa.String(length=50), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=True),
    sa.Column('target_distance_km', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_workout_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('workout_type_id', sa.String(length=36), nullable=False),
    sa.Column('distance_meters', sa.Integer(), nullable=True),
    sa.Column('times_seconds', sa.JSON(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('rest_type', sa.String(length=50), nullable=True),
    sa.Column('rest_duration', sa.Integer(), nullable=True),
    sa.Column('intensity', sa.Integer(), nullable=True),
    sa.Column('session_period', sa.String(length=50), nullable=True),
    sa.Column('warmup_distance', sa.Integer(), nullable=True),
    sa.Column('warmup_time', sa.Integer(), nullable=True),
    sa.Column('main_distance', sa.Integer(), nullable=True),
    sa.Column('main_time', sa.Integer(), nullable=True),
    sa.Column('cooldown_distance', sa.Integer(), nullable=True),
    sa.Column('cooldown_time', sa.Integer(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workout_type_id'], ['workout_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_workout_plan_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('plan_id', sa.String(length=36), nullable=False),
    sa.Column('template_id', sa.String(length=36), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('order_in_day', sa.Integer(), nullable=True),
    sa.Column('distance_override', sa.Integer(), nullable=True),
    sa.Column('intensity_override', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['custom_workout_plans.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['custom_workout_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('custom_workout_plan_items')
    op.drop_table('custom_workout_templates')
    op.drop_table('custom_workout_plans')
    # ### end Alembic commands ###
