"""add_interval_analysis_tables

Revision ID: 3051f9aeb603
Revises: b02e2566de98
Create Date: 2025-09-24 14:06:14.535047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3051f9aeb603'
down_revision: Union[str, None] = 'b02e2566de98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
