"""add_username_and_is_verified_to_users

Revision ID: 5cc1e2ccbe36
Revises: a5141b5c8992
Create Date: 2025-09-25 13:18:33.881272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5cc1e2ccbe36'
down_revision: Union[str, None] = 'a5141b5c8992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('race_results', sa.Column('race_type', sa.String(length=10), nullable=True))  # 既に存在するためコメントアウト
    # op.add_column('race_results', sa.Column('distance_meters', sa.Integer(), nullable=False))  # 既に存在する可能性があるためコメントアウト
    # op.add_column('race_results', sa.Column('custom_distance_m', sa.Integer(), nullable=True))  # 既に存在する可能性があるためコメントアウト
    op.alter_column('race_results', 'race_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('race_results', 'race_type_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('race_results', 'pace_seconds',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.create_foreign_key(None, 'race_results', 'race_types', ['race_type_id'], ['id'])
    op.drop_column('race_results', 'event')
    op.add_column('users', sa.Column('username', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=True))
    op.alter_column('users', 'gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('male', 'female', 'other', name='genderenum'),
               existing_nullable=True)
    op.alter_column('users', 'user_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('athlete', 'serious_runner', 'casual_runner', name='usertypeenum'),
               existing_nullable=True)
    op.create_unique_constraint(None, 'users', ['username'])
    op.alter_column('workouts', 'completion_rate',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # op.drop_column('workouts', 'distance_meters')  # 既に存在しない可能性があるためコメントアウト
    # op.drop_column('workouts', 'times_seconds')  # 既に存在しない可能性があるためコメントアウト
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('workouts', sa.Column('times_seconds', sqlite.JSON(), nullable=True))  # 既に存在しない可能性があるためコメントアウト
    # op.add_column('workouts', sa.Column('distance_meters', sa.INTEGER(), nullable=True))  # 既に存在しない可能性があるためコメントアウト
    op.alter_column('workouts', 'completion_rate',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'user_type',
               existing_type=sa.Enum('athlete', 'serious_runner', 'casual_runner', name='usertypeenum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('users', 'gender',
               existing_type=sa.Enum('male', 'female', 'other', name='genderenum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True)
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'username')
    op.add_column('race_results', sa.Column('event', sa.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'race_results', type_='foreignkey')
    op.alter_column('race_results', 'pace_seconds',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('race_results', 'race_type_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('race_results', 'race_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # op.drop_column('race_results', 'custom_distance_m')  # 既に存在する可能性があるためコメントアウト
    # op.drop_column('race_results', 'distance_meters')  # 既に存在する可能性があるためコメントアウト
    # op.drop_column('race_results', 'race_type')  # 既に存在するためコメントアウト
    # ### end Alembic commands ###
