"""add_daily_metrics_tables

Revision ID: d4bb47b6507f
Revises: 3051f9aeb603
Create Date: 2025-09-24 14:08:43.353073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4bb47b6507f'
down_revision: Union[str, None] = '3051f9aeb603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
